### ISSUE TITLE
Setup complete Union bundle

### ISSUE THREAD

**Issue by alvesjtiago** [meetunion/union#36]
How should we deal with the initial setup of Union + Admin + Frontend? Should we create a utility CLI package to set it all up? Should we try to combine everything on a single repo and provide a click to deploy button?

We need to decide what the minimum viable product should contain in order to deliver the first version and after that iterate and improve constantly with user's feedback.

**Comment by jackveiga** [comment]
I think at first our focus should click to deploy button so anyone can easily use it, and later on, think of ways of helping users deploy to their own infra for more advance users.
